
spring:
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USERNAME}
        password: ${PROD_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
#            ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
              format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect



management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
